### PR TITLE
Using natsort to determine facet order

### PR DESCRIPTION
**Pull request by kristjaneerik**
This addresses https://github.com/bpteague/cytoflow/issues/256 and shouldn't really mess up anything unexpectedly...

Tests run fine but I also haven't added any additional tests, I just verified that it worked with some data I was working with where a need for natural sorting came up. Depending on what gets merged first, I'd add tests in or after #270.

GUI tests just had the failures mentioned in @271 so should be okay after that is in.

### CODE REVIEW

**Comment by kristjaneerik** [comment]
I've merged in master. The latest commit also allows overriding the `col_order`, `row_order`, and `hue_order` parameters -- I've found this super useful!

**Comment by bpteague** [comment]
`natsort` looks cool (: Sure, let's use it. And I like the order overrides -- very `seaborn`esqe. Two requests before I merge the PR:

- Please add the new `kwargs` to the doc string -- this will make sure they show up in the API docs. (And because of some sphinx magic, they'll show up in the API docs of all the classes that derive from this one.)
- Do we have to alias `natsorted` to `sorter`? It's not an object that does something (ie, not a parametarizable sorter), but rather a filter function. It's a dumb aesthetic thing, I know, but please let's use the API that `natsort` gave us (;

**Comment by kristjaneerik** [comment]
Sure thing! How are the docs generated?

The `sorter = natsorted` was a relic from when I was playing with different sorters. Removing.

I'll also be adding some tests in a bit.

**Comment by bpteague** [comment]
Have a look at, eg, the last two lines of `cytoflow.views.histogram`:

```
util.expand_class_attributes(HistogramView)
util.expand_method_parameters(HistogramView, HistogramView.plot)
```

Those two functions parse the doc strings of all the parent classes, pull out the attributes (for classes) and parameters (for functions), and merge them into the docstrings of the child class. So if you document a new parameter in the base class, it shows up in the `sphinx`-generated docs of all of the children classes (:

**Comment by kristjaneerik** [comment]
Oh I was wondering more about the actual generation -- do I need to run a command to have the files updated in order to include the changes in the repo?

**Comment by bpteague** [comment]
> Oh I was wondering more about the actual generation -- do I need to run a command to have the files updated in order to include the changes in the repo?

Nope! Happens at `import` time.

**Comment by bpteague** [comment]
> > Oh I was wondering more about the actual generation -- do I need to run a command to have the files updated in order to include the changes in the repo?
> 
> Nope! Happens at `import` time.

(Or at package build time (; )

**Comment by kristjaneerik** [comment]
Sounds good! This should be ready for review again.

**Comment by bpteague** [comment]
Merged.

**Pull request merged**
